"use client";
import Link from "next/link";
import { useState, type ReactNode } from "react";
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Code2, Copy, FileText, KeyRound, Network, Plus, Search, ShieldCheck, Terminal, Upload, Zap } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { documents, incidents, requests, sections, services } from "./console-data";
import { useConsole } from "./console-shell";

export function Panel({ title, action, children, className = "" }: { title?: string; action?: ReactNode; children: ReactNode; className?: string }) {
  return <section className={`dev-panel ${className}`}>{title && <div className="dev-panel-head"><h2>{title}</h2>{action}</div>}{children}</section>;
}
function Badge({ children, warning = false }: { children: ReactNode; warning?: boolean }) { return <span className={`dev-badge ${warning ? "warning" : ""}`}>{children}</span>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <select className="dev-select" aria-label={label} value={value} onChange={e => onChange(e.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select>; }
function SearchField({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="dev-search"><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)} /></label>; }
function Stats({ items }: { items: [string, string, string][] }) { return <div className="dev-stats">{items.map(([label, value, detail], index) => <Panel key={label}><span className="dev-eyebrow">{label}</span><div className="dev-stat-value">{value}</div><div className="dev-stat-detail"><span className="dev-dot" />{detail}</div><div className="dev-spark" aria-hidden="true">{Array.from({ length: 28 }, (_, i) => <i key={i} style={{ height: `${18 + ((i * 17 + index * 11) % 72)}%` }} />)}</div></Panel>)}</div>; }
function CopyCode({ code }: { code: string }) { const [message, setMessage] = useState(""); return <div className="dev-code"><button className="dev-icon" aria-label="Copy code" onClick={async () => { try { await navigator.clipboard.writeText(code); setMessage("Copied"); } catch { setMessage("Select code to copy"); } }}>{message === "Copied" ? <Check size={15} /> : <Copy size={15} />}</button><pre><code>{code}</code></pre><span role="status">{message}</span></div>; }

export function ConsolePage({ section }: { section: string }) {
  const { openKey } = useConsole();
  return <><header className="dev-page-header"><div><p className="dev-eyebrow">TRUE MEMORY / {section === "overview" ? "CONSOLE" : section.replaceAll("-", " ")}</p><h1>{sections[section][0]}</h1><p>{sections[section][1]}</p></div><div className="dev-header-actions">{section === "api-keys" || section === "overview" ? <button className="dev-button primary" onClick={openKey}><Plus size={15} /> Create API key</button> : section === "documents" ? <Link className="dev-button primary" href="/developer/import"><Upload size={15} /> Import data</Link> : <Link className="dev-button" href="/developer/agents"><Code2 size={15} /> Integration guide <ArrowUpRight size={13} /></Link>}</div></header>
    {section === "overview" && <Overview />}
    {section === "requests" && <Requests />}
    {section === "health" && <Health />}
    {section === "incidents" && <Incidents />}
    {section === "documents" && <Documents />}
    {section === "tags" && <Tags />}
    {section === "playground" && <Playground />}
    {section === "graph" && <Graph />}
    {section === "connectors" && <Connectors />}
    {section === "import" && <Import />}
    {section === "api-keys" && <Keys />}
    {section === "agents" && <Agents />}
    {section === "insights" && <Insights />}
    {section === "team" && <Team />}
    {section === "billing" && <Billing />}
    {section === "settings" && <Settings />}
  </>;
}

function Overview() {
  const [range, setRange] = useState("30d");
  return <><div className="dev-welcome"><div><span className="dev-kicker"><Terminal size={15} /> BUILT FOR DEVELOPERS</span><h2>A little context.<br />A lot more possibility.</h2><p>Connect your agents, inspect every request,<br />and give your applications a memory.</p><Link className="dev-button primary" href="/developer/playground">Open playground <ArrowRight size={15} /></Link></div><div className="dev-orbit" aria-hidden="true"><span>tm</span><i /><i /><i /></div><div className="dev-welcome-code"><span>01 / REMEMBER</span><code>memory.remember(context)</code><span>02 / RETRIEVE</span><code>memory.search(query)</code><span>03 / BUILD</span><code>agent.run(withMemory)</code></div></div>
    <Stats items={[["Documents", "4", "3 indexed · 1 processing"], ["Memories", "84", "Across 3 container tags"], ["Sample requests", "18", "16 successful responses"], ["Connected agents", "3", "API + MCP integrations"]]} />
    <div className="dev-grid-main"><Panel title="Request volume" action={<div className="dev-segments">{["1d", "7d", "30d"].map(r => <button key={r} aria-pressed={range === r} onClick={() => setRange(r)}>{r}</button>)}</div>}><div className="dev-chart-summary"><strong>{range === "1d" ? "18" : range === "7d" ? "126" : "540"}<span>sample requests</span></strong><div className="dev-legend"><span><i />Search</span><span><i />Write</span><span><i />Profile</span></div></div><div className="dev-volume" role="img" aria-label={`Illustrative request volume for ${range}`}><div className="dev-chart-axis"><span>600</span><span>400</span><span>200</span><span>0</span></div>{Array.from({ length: range === "1d" ? 24 : range === "7d" ? 14 : 30 }, (_, i) => <div className="dev-volume-column" key={i} style={{ height: `${28 + (i * 23 + Number(range.slice(0, -1))) % 69}%` }}><i /><i /><i /></div>)}</div><div className="dev-chart-labels"><span>{range} ago</span><span>Sample traffic · UTC</span><span>Now</span></div></Panel>
    <Panel title="Infrastructure" action={<Link href="/developer/health"><ArrowUpRight size={16} /></Link>}><div className="dev-health-summary"><span className="dev-status-icon"><Activity size={23} /></span><h3>Partially degraded</h3><p>Ingestion latency is being monitored.</p><Badge warning>1 active sample incident</Badge></div>{services.slice(0, 4).map((s, i) => <div className="dev-service-mini" key={s}><span>{s}</span><span><i className={`dev-dot ${i === 2 ? "amber" : ""}`} />{i === 2 ? "Monitoring" : "Operational"}</span></div>)}<Link className="dev-panel-link" href="/developer/incidents">View incident timeline <ArrowRight size={14} /></Link></Panel></div>
    <div className="dev-grid-two"><Panel title="Recent documents" action={<Link href="/developer/documents">View all ↗</Link>}>{documents.slice(0, 3).map(d => <Link key={d.id} className="dev-list-row" href="/developer/documents"><FileText size={16} /><div><strong>{d.title}</strong><small>{d.tag}</small></div><span>{d.time}</span></Link>)}</Panel><Panel title="Quick start" action={<Badge>REST API</Badge>}><div className="dev-padded"><p className="dev-muted">Store your first memory using an API key.</p><CopyCode code={`curl -X POST ${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/v1/memories \\\n  -H "Authorization: Bearer $TRUEMEMORY_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d '{"key":"editor","content":"I use VS Code","source":"app"}'`} /></div></Panel></div>
    <div className="dev-resource-grid">{[["playground", "Test retrieval", "Inspect context before shipping."], ["agents", "Connect an agent", "REST, SDKs, and MCP configuration."], ["api-keys", "Manage API keys", "Give your applications memory access."], ["health", "Monitor your system", "Availability and incident timelines."]].map(([id, title, detail]) => <Link className="dev-resource" key={id} href={`/developer/${id}`}><ArrowUpRight size={17} /><h3>{title}</h3><p>{detail}</p></Link>)}</div>
  </>;
}

function Requests() {
  const [type, setType] = useState("All types"); const [status, setStatus] = useState("All statuses"); const [range, setRange] = useState("Last 30 days"); const [page, setPage] = useState(0); const [selected, setSelected] = useState<typeof requests[number] | null>(null);
  const filtered = requests.filter(r => (type === "All types" || r.type === type) && (status === "All statuses" || (status === "2xx Success" ? r.status < 300 : r.status >= 400)) && (range !== "Last hour" || r.minutes <= 60));
  const successes = filtered.filter(r => r.status < 300).length; const average = filtered.length ? Math.round(filtered.reduce((a, r) => a + r.duration, 0) / filtered.length) : 0;
  return <><div className="dev-toolbar"><Select label="Request type" value={type} onChange={v => { setType(v); setPage(0); }} options={["All types", "search", "add", "profile"]} /><Select label="Response status" value={status} onChange={v => { setStatus(v); setPage(0); }} options={["All statuses", "2xx Success", "4xx / 5xx Errors"]} /><Select label="Request period" value={range} onChange={v => { setRange(v); setPage(0); }} options={["Last 30 days", "Last hour"]} /><span className="dev-toolbar-note">Click a request to inspect its trace</span></div>
    <Stats items={[["By type", String(filtered.length), `${filtered.filter(r => r.type === "search").length} search · ${filtered.filter(r => r.type === "add").length} add · ${filtered.filter(r => r.type === "profile").length} profile`], ["2xx responses", `${successes} / ${filtered.length}`, `${filtered.length ? ((successes / filtered.length) * 100).toFixed(1) : 0}% success rate`], ["Average latency", `${average} ms`, range.toLowerCase()]]} />
    <Panel><div className="dev-table-wrap"><table><thead><tr><th>Type / Request ID</th><th>Container</th><th>Status</th><th>Duration</th><th>Time</th><th /></tr></thead><tbody>{filtered.slice(page * 8, page * 8 + 8).map(r => <tr key={r.id}><td><button className="dev-text-button" onClick={() => setSelected(r)}><span className={`dev-type-dot ${r.type}`} />{r.type}<small>{r.id}</small></button></td><td><code>{r.tag}</code></td><td><Badge warning={r.status >= 400}>{r.status}</Badge></td><td><div className="dev-latency"><code>{r.duration} ms</code><i style={{ width: `${r.duration / 7}px` }} /></div></td><td>{r.minutes}m ago</td><td><button className="dev-icon" aria-label={`Inspect ${r.id}`} onClick={() => setSelected(r)}><ChevronRight size={15} /></button></td></tr>)}</tbody></table>{!filtered.length && <div className="dev-empty">No requests match these filters.</div>}</div><div className="dev-table-footer"><span>{filtered.length ? page * 8 + 1 : 0}–{Math.min(page * 8 + 8, filtered.length)} of {filtered.length} requests</span><div><button className="dev-icon" aria-label="Previous requests" disabled={page === 0} onClick={() => setPage(page - 1)}><ChevronLeft size={15} /></button><button className="dev-icon" aria-label="Next requests" disabled={(page + 1) * 8 >= filtered.length} onClick={() => setPage(page + 1)}><ChevronRight size={15} /></button></div></div></Panel>
    <Dialog open={!!selected} onOpenChange={open => !open && setSelected(null)}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Request trace</DialogTitle><DialogDescription>{selected?.id} · Sample request</DialogDescription></DialogHeader>{selected && <div className="space-y-4"><p><code>{selected.type === "profile" ? "GET" : "POST"} {selected.path}</code></p><p>Status {selected.status} · {selected.duration} ms · {selected.tag}</p><pre className="overflow-auto rounded-lg border p-4 text-xs">{JSON.stringify({ request_id: selected.id, container_tag: selected.tag, status: selected.status, timings: { authentication: 4, retrieval: Math.max(1, selected.duration - 10), response: 6 }, error: selected.status === 429 ? "Rate limit exceeded" : selected.status === 500 ? "Internal server error" : null }, null, 2)}</pre></div>}</DialogContent></Dialog>
  </>;
}

function Health() {
  const [range, setRange] = useState("90 days");
  return <><div className="dev-health-banner"><span className="dev-status-icon"><Activity size={24} /></span><div><h2>Some systems are experiencing delays</h2><p>Memory reads are operational. Ingestion latency is being monitored.</p></div><Badge warning>Sample status</Badge></div><div className="dev-grid-main"><Panel title="Service availability" action={<Select label="Uptime period" value={range} onChange={setRange} options={["90 days", "30 days", "7 days"]} />}><div className="dev-uptime-list">{services.map((service, index) => <div className="dev-uptime-row" key={service}><div><strong>{service}</strong><span><span className={`dev-dot ${index === 2 ? "amber" : ""}`} />{index === 2 ? "Degraded performance" : "Operational"}</span></div><div className="dev-uptime-bars" role="img" aria-label={`${service}: sample uptime ${index === 2 ? "99.82" : "99.99"} percent over ${range}`}>{Array.from({ length: parseInt(range) }, (_, day) => <i key={day} className={index === 2 && day > parseInt(range) - 4 ? "affected" : ""} title={`Day ${day + 1}: ${index === 2 && day > parseInt(range) - 4 ? "Ingestion delays" : "Operational"}`} />)}</div><div className="dev-uptime-labels"><span>{range} ago</span><span>{index === 2 ? "99.82" : "99.99"}% uptime</span><span>Today</span></div></div>)}</div></Panel><div className="dev-stack"><Panel title="Active incident"><div className="dev-padded"><div className="dev-inline"><Badge warning>Monitoring</Badge><span className="dev-muted">INC-024</span></div><h3 className="dev-spaced">Elevated ingestion latency</h3><p className="dev-muted">Ingestion workers are recovering. Existing memories remain available.</p><div className="dev-incident-meta"><span><Clock3 size={14} />32 minutes</span><span>Minor impact</span></div><Link className="dev-button" href="/developer/incidents">View timeline <ArrowRight size={14} /></Link></div></Panel><Panel title="Response overview"><div className="dev-padded"><div className="dev-big-number">126<span>ms median</span></div><p className="dev-muted">Search response time · sample</p><div className="dev-mini-area" aria-hidden="true">{Array.from({ length: 28 }, (_, i) => <i key={i} style={{ height: `${25 + i * 13 % 70}%` }} />)}</div><div className="dev-inline dev-muted"><span>p95: 412 ms</span><span>p99: 641 ms</span></div></div></Panel></div></div><Panel title="Recent incidents" action={<Link href="/developer/incidents">All incidents ↗</Link>}>{incidents.map(i => <Link className="dev-list-row" key={i.id} href="/developer/incidents"><CheckCircle2 size={18} /><div><strong>{i.title}</strong><small>{i.date} · {i.service}</small></div><Badge warning={i.status !== "Resolved"}>{i.status}</Badge></Link>)}</Panel></>;
}

function Incidents() {
  const [status, setStatus] = useState("All incidents"); const [selected, setSelected] = useState(incidents[0]);
  const filtered = incidents.filter(i => status === "All incidents" || i.status === status);
  return <><Stats items={[["Active incidents", "1", "Monitoring ingestion recovery"], ["Resolved this month", "1", "18 minutes to resolution"], ["Affected services", "1 / 6", "Memory reads operational"]]} /><div className="dev-toolbar"><Select label="Incident status" value={status} onChange={setStatus} options={["All incidents", "Monitoring", "Resolved"]} /><span className="dev-toolbar-note">Sample incident history · all timestamps UTC</span></div><div className="dev-grid-two"><Panel title="Incident history">{filtered.map(i => <button className={`dev-incident-item ${selected.id === i.id ? "selected" : ""}`} key={i.id} onClick={() => setSelected(i)}><div className="dev-inline"><span className="dev-eyebrow">{i.id} · {i.date}</span><Badge warning={i.status !== "Resolved"}>{i.status}</Badge></div><h3>{i.title}</h3><p>{i.service} <span>·</span> {i.severity} <span>·</span> {i.duration}</p><span className="dev-incident-open">View timeline <ArrowRight size={13} /></span></button>)}</Panel><Panel title="Incident timeline" action={<span className="dev-eyebrow">{selected.id}</span>}><div className="dev-padded"><Badge warning={selected.status !== "Resolved"}>{selected.status}</Badge><h2 className="dev-spaced">{selected.title}</h2><p className="dev-muted">{selected.date} · {selected.service} · {selected.severity} impact</p><ol className="dev-timeline">{selected.updates.map(([time, stage, description]) => <li key={time}><span className={`dev-timeline-dot ${stage === "Resolved" ? "resolved" : ""}`} /><div className="dev-inline"><h3>{stage}</h3><time>{time} UTC</time></div><p>{description}</p></li>)}</ol><div className="dev-note"><ShieldCheck size={16} /><span>This is a preview of incident response. No external status provider is connected.</span></div></div></Panel></div></>;
}

function Documents() {
  const [query, setQuery] = useState(""); const [tag, setTag] = useState("All tags"); const [status, setStatus] = useState("All statuses"); const [selected, setSelected] = useState<typeof documents[number] | null>(null);
  const filtered = documents.filter(d => d.title.toLowerCase().includes(query.toLowerCase()) && (tag === "All tags" || d.tag === tag) && (status === "All statuses" || d.status === status));
  return <><div className="dev-toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search documents…" /><Select label="Document container" value={tag} onChange={setTag} options={["All tags", "engineering", "support-agent", "personal-assistant"]} /><Select label="Document status" value={status} onChange={setStatus} options={["All statuses", "Indexed", "Processing"]} /></div><Panel><div className="dev-table-wrap"><table><thead><tr><th>Document</th><th>Container tag</th><th>Memories</th><th>Status</th><th>Updated</th></tr></thead><tbody>{filtered.map(d => <tr key={d.id}><td><button className="dev-text-button" onClick={() => setSelected(d)}><FileText size={16} />{d.title}<small>{d.id}</small></button></td><td><code>{d.tag}</code></td><td>{d.memories}</td><td><Badge warning={d.status === "Processing"}>{d.status}</Badge></td><td>{d.time}</td></tr>)}</tbody></table>{!filtered.length && <div className="dev-empty">No documents match your filters.</div>}</div><div className="dev-table-footer">{filtered.length} documents · {filtered.reduce((n, d) => n + d.memories, 0)} memories</div></Panel><Dialog open={!!selected} onOpenChange={v => !v && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>Sample document metadata</DialogDescription></DialogHeader><pre className="overflow-auto text-xs">{JSON.stringify(selected, null, 2)}</pre></DialogContent></Dialog></>;
}

function Tags() { const [query, setQuery] = useState(""); return <><div className="dev-toolbar"><SearchField value={query} onChange={setQuery} placeholder="Search container tags…" /></div><Panel><div className="dev-table-wrap"><table><thead><tr><th>Container tag</th><th>Documents</th><th>Memories</th><th>Access</th><th /></tr></thead><tbody>{["engineering", "support-agent", "personal-assistant"].filter(t => t.includes(query.toLowerCase())).map(tag => <tr key={tag}><td><strong>{tag}</strong><small>Isolated memory namespace</small></td><td>{documents.filter(d => d.tag === tag).length}</td><td>{documents.filter(d => d.tag === tag).reduce((n, d) => n + d.memories, 0)}</td><td><Badge>Scoped</Badge></td><td><Link className="dev-button" href="/developer/playground">Explore <ArrowUpRight size={13} /></Link></td></tr>)}</tbody></table></div></Panel></>; }

function Playground() {
  const [query, setQuery] = useState(""); const [result, setResult] = useState(""); const [mode, setMode] = useState("Search"); const [tag, setTag] = useState("All containers"); const [limit, setLimit] = useState("5"); const [strictness, setStrictness] = useState("0.4"); const [rerank, setRerank] = useState(true);
  const matches = documents.filter(d => (tag === "All containers" || d.tag === tag) && `${d.title} ${d.tag}`.toLowerCase().split(/[\s-]+/).some(word => result.toLowerCase().includes(word))).slice(0, Number(limit));
  return <div className="dev-playground"><Panel className="dev-playground-main"><div className="dev-panel-head"><div className="dev-segments">{["Search", "Chat"].map(m => <button key={m} aria-pressed={mode === m} onClick={() => { setMode(m); setResult(""); }}>{m}</button>)}</div><Badge>Local preview</Badge></div><div className="dev-playground-results">{!result ? <div className="dev-empty"><span className="dev-empty-icon"><Network size={26} /></span><h2>Give your query some context.</h2><p>Search sample documents and inspect retrieval settings.</p><div className="dev-suggestions">{["Agent onboarding", "Product architecture", "Customer preferences"].map(q => <button key={q} onClick={() => setQuery(q)}>{q}<ArrowUpRight size={12} /></button>)}</div></div> : <div className="dev-padded"><p className="dev-eyebrow">{mode === "Chat" ? "CONTEXT PREVIEW · NO MODEL CONNECTED" : `${matches.length} SAMPLE MATCHES`}</p><h3 className="dev-spaced">{result}</h3>{matches.map(d => <article key={d.id} className="dev-result"><div className="dev-inline"><strong>{d.title}</strong><Badge>Keyword match</Badge></div><p>{d.tag} · {d.memories} stored memories</p><small>{d.id}</small></article>)}{!matches.length && <p className="dev-muted">No sample documents matched. Try “agent”, “architecture”, or “preferences”.</p>}</div>}</div><form className="dev-query" onSubmit={e => { e.preventDefault(); setResult(query.trim()); }}><label className="sr-only" htmlFor="query">Memory query</label><textarea id="query" value={query} onChange={e => setQuery(e.target.value)} placeholder="Ask something about your memory…" /><div><span>Preview · keyword search</span><button className="dev-button primary" disabled={!query.trim()}><ArrowRight size={16} /> Run query</button></div></form></Panel><Panel title="Memory settings" action={<button className="dev-text-button" onClick={() => { setTag("All containers"); setLimit("5"); setStrictness("0.4"); setRerank(true); }}>Reset</button>}><div className="dev-form dev-padded"><label>Container<Select label="Playground container" value={tag} onChange={setTag} options={["All containers", "engineering", "support-agent", "personal-assistant"]} /></label><label>Memories retrieved<Select label="Result limit" value={limit} onChange={setLimit} options={["3", "5", "10"]} /></label><label>Match threshold <span>{strictness}</span><input type="range" min="0" max="1" step="0.1" value={strictness} onChange={e => setStrictness(e.target.value)} /></label><label className="dev-toggle-label">Rerank results<input type="checkbox" checked={rerank} onChange={e => setRerank(e.target.checked)} /></label><p className="dev-muted">Threshold and reranking configure the request preview. Local results use keyword matching.</p><h3>Request configuration</h3><CopyCode code={JSON.stringify({ query, container_tag: tag === "All containers" ? undefined : tag, limit: Number(limit), threshold: Number(strictness), rerank }, null, 2)} /></div></Panel></div>;
}

function Graph() {
  const [zoom, setZoom] = useState(100); const [selected, setSelected] = useState("TrueMemory");
  const nodes = [["TrueMemory", 50, 48], ["Engineering", 22, 25], ["Support agent", 78, 24], ["Preferences", 24, 74], ["MCP gateway", 77, 74], ["Architecture", 12, 47], ["Onboarding", 88, 48]] as const;
  return <Panel><div className="dev-graph"><div className="dev-graph-canvas" style={{ transform: `scale(${zoom / 100})` }}><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{nodes.slice(1).map(([name, x, y]) => <line key={name} x1="50" y1="48" x2={x} y2={y} />)}</svg>{nodes.map(([name, x, y]) => <button key={name} className={`dev-graph-node ${selected === name ? "selected" : ""}`} style={{ left: `${x}%`, top: `${y}%` }} onClick={() => setSelected(name)}><Network size={20} /><span>{name}</span></button>)}</div><div className="dev-graph-controls"><button className="dev-button" onClick={() => setZoom(100)}>Fit</button><button className="dev-icon" aria-label="Zoom out" disabled={zoom <= 60} onClick={() => setZoom(zoom - 10)}>−</button><span>{zoom}%</span><button className="dev-icon" aria-label="Zoom in" disabled={zoom >= 140} onClick={() => setZoom(zoom + 10)}>+</button></div><div className="dev-graph-detail"><span className="dev-eyebrow">SELECTED NODE</span><h3>{selected}</h3><p>Sample relationship · {selected === "TrueMemory" ? "6 connections" : "1 connection"}</p><Link href="/developer/documents">Explore documents ↗</Link></div></div></Panel>;
}

function Connectors() {
  const [query, setQuery] = useState(""); const [type, setType] = useState("All"); const [selected, setSelected] = useState("");
  const list = [["Google Drive", "OAuth", "Documents and shared knowledge"], ["Notion", "OAuth", "Pages, databases, and team wikis"], ["GitHub", "OAuth", "Repositories and engineering context"], ["Amazon S3", "Services", "Files from your object storage"], ["Web crawler", "Services", "Public sites and documentation"], ["Slack", "OAuth", "Conversations and team decisions"]];
  return <><div className="dev-toolbar"><div className="dev-segments">{["All", "OAuth", "Services"].map(t => <button key={t} aria-pressed={type === t} onClick={() => setType(t)}>{t}</button>)}</div><SearchField value={query} onChange={setQuery} placeholder="Search connectors…" /></div><div className="dev-connector-grid">{list.filter(([name, category]) => name.toLowerCase().includes(query.toLowerCase()) && (type === "All" || type === category)).map(([name, category, description]) => <Panel key={name}><div className="dev-padded"><div className="dev-inline"><span className="dev-connector-icon">{name[0]}</span><span className="dev-eyebrow">{category}</span></div><h3 className="dev-spaced">{name}</h3><p className="dev-muted">{description}</p><button className="dev-button" onClick={() => setSelected(name)}>View setup <ArrowUpRight size={13} /></button></div></Panel>)}</div><Dialog open={!!selected} onOpenChange={v => !v && setSelected("")}><DialogContent><DialogHeader><DialogTitle>{selected} integration</DialogTitle><DialogDescription>Connector setup preview</DialogDescription></DialogHeader><p>Choose a source, authorize access, and select a container tag to keep imported context isolated.</p><p>OAuth and sync controls are not connected in this console preview.</p><Link href="/connectors" className="underline">Open existing TrueMemory integrations</Link></DialogContent></Dialog></>;
}

function Import() {
  const [files, setFiles] = useState<string[]>([]); const [url, setUrl] = useState(""); const [tag, setTag] = useState("engineering"); const [message, setMessage] = useState("");
  function stage(list: FileList | null) { if (list) setFiles(prev => [...new Set([...prev, ...Array.from(list).map(f => f.name)])]); }
  return <div className="dev-grid-main"><Panel><div className="dev-padded"><label className="dev-dropzone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); stage(e.dataTransfer.files); }}><Upload size={28} /><strong>Drop files here, or browse</strong><span>TXT · MD · JSON · PDF · DOCX</span><input type="file" multiple accept=".txt,.md,.json,.pdf,.docx" onChange={e => stage(e.target.files)} /></label><form className="dev-url-form" onSubmit={e => { e.preventDefault(); setFiles(prev => [...new Set([...prev, url])]); setUrl(""); }}><label htmlFor="source-url">Add from the web</label><div><input id="source-url" type="url" required value={url} onChange={e => setUrl(e.target.value)} placeholder="https://example.com/docs" /><button className="dev-button" disabled={!url}>Add</button></div></form><div className="dev-setting-row"><div><strong>Container tag</strong><p>Group staged content under one namespace.</p></div><Select label="Import container" value={tag} onChange={setTag} options={["engineering", "support-agent", "personal-assistant"]} /></div>{files.map(f => <div className="dev-staged" key={f}><FileText size={14} /><span>{f}</span><button className="dev-icon" aria-label={`Remove ${f}`} onClick={() => setFiles(files.filter(item => item !== f))}>×</button></div>)}<div className="dev-inline"><span className="dev-muted">{files.length} sources staged</span><button className="dev-button primary" disabled={!files.length} onClick={() => setMessage(`${files.length} sources staged for ${tag}. Upload processing is not connected in this preview; no files were sent.`)}>Validate staged import</button></div><p role="status" className="dev-muted">{message}</p></div></Panel><Panel title="Processing"><div className="dev-empty"><Zap size={25} /><h3>No imports running</h3><p>Staging is local to this page. Use your API ingestion workflow to upload source content.</p><Link className="dev-button" href="/developer/agents">Read API guide</Link></div></Panel></div>;
}

function Keys() { const { openKey } = useConsole(); return <><div className="dev-note"><ShieldCheck size={18} /><span>Keys are created through your existing authenticated API. Keep secrets on the server and use an expiry appropriate for your application.</span></div><Panel title="Application credentials"><div className="dev-empty dev-empty-large"><span className="dev-empty-icon"><KeyRound size={27} /></span><h2>Create a key for your application</h2><p>This console does not list existing credentials yet. New secrets are shown once at creation.</p><button className="dev-button primary" onClick={openKey}><Plus size={15} />Create API key</button></div></Panel><div className="dev-grid-two"><Panel title="Memory access"><div className="dev-padded"><p className="dev-muted">New keys use the memory scope supported by the current backend.</p></div></Panel><Panel title="Authentication"><div className="dev-padded"><CopyCode code='Authorization: Bearer $TRUEMEMORY_TOKEN' /></div></Panel></div></>; }

function Agents() {
  const [tab, setTab] = useState("REST"); const base = process.env.NEXT_PUBLIC_API_URL || "https://truememory.onrender.com";
  const snippets: Record<string, string> = { REST: `curl -X POST ${base}/v1/memories \\\n  -H "Authorization: Bearer $TRUEMEMORY_TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d '{"key":"editor","content":"I use VS Code","source":"app"}'`, TypeScript: '// With an authenticated TrueMemory client:\nawait client.remember({\n  key: "editor",\n  content: "I use VS Code",\n  source: "app"\n});\nconst results = await client.search({ query: "editor" });', Python: '# With an authenticated TrueMemory client:\nclient.remember(\n    key="editor",\n    content="I use VS Code",\n    source="app"\n)\nresults = client.search(query="editor")', MCP: JSON.stringify({ mcpServers: { truememory: { url: `${base}/mcp`, headers: { Authorization: "Bearer <YOUR_TOKEN>" } } } }, null, 2) };
  return <><div className="dev-resource-grid">{[["1", "Create a key", "Get a scoped credential for memory access."], ["2", "Choose an interface", "Use REST, an SDK, or your agent's MCP client."], ["3", "Store context", "Capture a decision, preference, or fact."], ["4", "Retrieve memory", "Bring relevant context into the next session."]].map(([n, title, text]) => <div className="dev-resource" key={n}><span className="dev-step">{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div><Panel title="Integration examples" action={<Badge>TrueMemory</Badge>}><div className="dev-padded"><div className="dev-segments">{Object.keys(snippets).map(t => <button aria-pressed={tab === t} key={t} onClick={() => setTab(t)}>{t}</button>)}</div><CopyCode code={snippets[tab]} /><p className="dev-muted">Use your configured backend URL and a real API token. SDK snippets assume an initialized client.</p></div></Panel><Panel title="Agent connection checklist"><div className="dev-padded dev-checklist">{["Configure the API or MCP endpoint", "Store your API key in a server-side secret", "Choose a container for each user or project", "Test a write and a retrieval request"].map(step => <label key={step}><input type="checkbox" />{step}</label>)}</div></Panel></>;
}

function Insights() { return <><Stats items={[["Active containers", "3", "Sample workspace"], ["Stored memories", "84", "From indexed documents"], ["Search requests", "6", "Sample request window"]]} /><Panel title="Context by container"><div className="dev-padded">{["engineering", "support-agent", "personal-assistant"].map(tag => { const count = documents.filter(d => d.tag === tag).reduce((n, d) => n + d.memories, 0); return <div className="dev-insight" key={tag}><div className="dev-inline"><strong>{tag}</strong><span>{count} memories</span></div><div className="dev-progress"><i style={{ width: `${count / 84 * 100}%` }} /></div></div>; })}</div></Panel></>; }
function Team() { return <Panel title="Sample workspace members"><div className="dev-table-wrap"><table><thead><tr><th>Member</th><th>Role</th><th>Access</th><th>Status</th></tr></thead><tbody>{[["Workspace owner", "owner@example.com", "Owner"], ["API engineer", "developer@example.com", "Developer"]].map(([name, email, role]) => <tr key={email}><td><strong>{name}</strong><small>{email}</small></td><td>{role}</td><td>{role === "Owner" ? "Full workspace" : "API & memory"}</td><td><Badge>Active</Badge></td></tr>)}</tbody></table></div><div className="dev-table-footer">Team administration is not connected in this preview.</div></Panel>; }
function Billing() { return <><Stats items={[["Sample plan", "Developer", "Illustrative usage only"], ["Requests used", "540", "Of 10,000 sample allowance"], ["Memory capacity", "84", "Of 1,000 sample allowance"]]} /><Panel title="Monthly consumption"><div className="dev-padded">{[["API requests", 5.4, "540 / 10,000"], ["Memory records", 8.4, "84 / 1,000"], ["Storage", 2, "20 MB / 1 GB"]].map(([name, percent, amount]) => <div className="dev-insight" key={name}><div className="dev-inline"><strong>{name}</strong><span>{amount}</span></div><div className="dev-progress"><i style={{ width: `${percent}%` }} /></div></div>)}</div></Panel><Panel title="Billing & invoices"><div className="dev-empty"><ArrowDownToLine size={24} /><h3>No preview invoices</h3><p>Open your existing subscription page for real account billing.</p><Link className="dev-button" href="/subscription">Manage subscription <ArrowUpRight size={14} /></Link></div></Panel></>; }
function Settings() {
  const [name, setName] = useState("Developer workspace"); const [context, setContext] = useState(false); const [retention, setRetention] = useState("30 days"); const [message, setMessage] = useState("");
  return <Panel title="Workspace preferences"><form className="dev-padded dev-form" onSubmit={e => { e.preventDefault(); setMessage("Preview preferences updated for this page. Server settings are not connected."); }}><div className="dev-setting-row"><div><strong>Workspace name</strong><p>The display name for this developer workspace.</p></div><input aria-label="Workspace name" required value={name} onChange={e => setName(e.target.value)} /></div><div className="dev-setting-row"><div><strong>Organization context</strong><p>Use workspace context when processing sources.</p></div><input aria-label="Organization context" type="checkbox" checked={context} onChange={e => setContext(e.target.checked)} /></div><div className="dev-setting-row"><div><strong>Request log retention</strong><p>How long request metadata is retained.</p></div><Select label="Log retention" value={retention} onChange={setRetention} options={["7 days", "30 days", "90 days"]} /></div><div className="dev-inline"><p role="status">{message}</p><button className="dev-button primary">Apply preview settings</button></div></form></Panel>;
}
