import Link from "next/link";
import { ArrowUpRight, ChevronDown, Command, Menu, Search } from "lucide-react";

export function PublicDocsShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-[#f8fafc] text-[#111827]">
    <header className="sticky top-0 z-40 border-b border-[#dbe3ee] bg-[#f8fafc]/95 backdrop-blur-xl">
      <div className="mx-auto flex h-[72px] max-w-[1320px] items-center justify-between gap-5 px-5 sm:px-8">
        <Link href="/" className="group flex shrink-0 items-center gap-2.5 text-sm font-semibold tracking-[-.02em]"><span className="grid size-8 place-items-center rounded-[10px] bg-[#111827] text-xs font-bold text-[#f6e879] shadow-sm transition group-hover:rotate-6">T</span><span>TrueMemory<span className="text-[#1769e0]">.</span></span></Link>
        <nav className="hidden items-center gap-1 rounded-full border border-[#e5eaf1] bg-white/60 p-1 text-xs text-[#566274] lg:flex"><NavLink href="/research">Research</NavLink><NavLink href="/brain">Memory Brain</NavLink><NavLink href="/docs">Docs</NavLink><NavLink href="/blog">Blog</NavLink><details className="group relative"><summary className="flex cursor-pointer list-none items-center gap-1 rounded-full px-3 py-2 outline-none transition hover:bg-[#eef5ff] hover:text-[#111827]">Products <ChevronDown className="size-3 transition group-open:rotate-180" /></summary><div className="absolute right-0 top-11 grid w-64 gap-1 rounded-2xl border border-[#dbe3ee] bg-white p-2 shadow-[0_18px_50px_rgba(15,23,42,.12)]"><MenuLink href="/brain" title="Memory Brain" body="A living memory for every agent" /><MenuLink href="/products/connectors" title="Connectors" body="Keep context close to the source" /><MenuLink href="/api-sdk" title="API & SDK" body="Build on the memory boundary" /></div></details></nav>
        <div className="flex items-center gap-2"><Link href="/docs" aria-label="Search documentation" className="hidden items-center gap-2 rounded-lg border border-[#dbe3ee] bg-white/60 px-2.5 py-2 text-xs text-[#94a3b8] transition hover:border-[#b9c7d9] hover:text-[#566274] md:inline-flex"><Search className="size-3.5" /><span className="hidden xl:inline">Search</span><kbd className="hidden rounded border border-[#dbe3ee] bg-[#f8fafc] px-1.5 py-0.5 font-mono text-[9px] xl:inline-flex"><Command className="mr-0.5 size-2.5" />K</kbd></Link><Link href="/login" className="hidden rounded-lg px-3 py-2 text-xs font-medium text-[#566274] transition hover:bg-white hover:text-[#111827] sm:inline-flex">Log in</Link><Link href="/signup" className="inline-flex items-center gap-1 rounded-lg bg-[#1769e0] px-3.5 py-2.5 text-xs font-semibold text-white shadow-[0_4px_12px_rgba(23,105,224,.2)] transition hover:bg-[#1258c0]">Start building <ArrowUpRight className="size-3" /></Link><Link href="/login" aria-label="Open account" className="grid size-9 place-items-center rounded-full border border-[#cbd5e1] bg-white text-[10px] font-bold text-[#1769e0] transition hover:border-[#1769e0] hover:shadow-sm">TM</Link><details className="relative lg:hidden"><summary aria-label="Open navigation" className="grid size-9 cursor-pointer list-none place-items-center rounded-lg border border-[#dbe3ee] bg-white"><Menu className="size-4" /></summary><div className="absolute right-0 top-12 w-64 rounded-2xl border border-[#dbe3ee] bg-white p-2 shadow-[0_18px_50px_rgba(15,23,42,.12)]"><MenuLink href="/research" title="Research" body="Experiments and benchmarks" /><MenuLink href="/brain" title="Memory Brain" body="A living memory for agents" /><MenuLink href="/docs" title="Documentation" body="Build with TrueMemory" /><MenuLink href="/blog" title="Blog" body="Notes from the team" /><MenuLink href="/products/connectors" title="Products" body="Explore the platform" /></div></details></div>
      </div>
    </header>
    {children}
    <footer className="border-t border-[#dbe3ee] bg-[#1769e0] text-white"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 py-14 sm:px-8 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><p className="max-w-xs text-2xl font-semibold tracking-[-.04em]">Memory infrastructure for AI agents.</p><p className="mt-3 max-w-xs text-sm leading-6 text-blue-100">One memory layer for applications, agents, and the teams building them.</p></div><FooterColumn title="Product" links={[["Memory Brain","/brain"],["Connectors","/products/connectors"],["API & SDK","/api-sdk"]]} /><FooterColumn title="Resources" links={[["Documentation","/docs"],["Research","/research"],["Blog","/blog"]]} /><FooterColumn title="Company" links={[["About","/"],["Security","/docs#isolation"],["Status","/status"]]} /></div><div className="mx-auto max-w-[1320px] border-t border-white/20 px-5 py-5 text-[10px] uppercase tracking-[.16em] text-blue-100 sm:px-8">© 2026 TrueMemory · Built from the verified repository</div></footer>
  </div>;
}

function FooterColumn({ title, links }: { title: string; links: string[][] }) { return <div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-100">{title}</p><div className="mt-4 space-y-3 text-sm">{links.map(([label, href]) => <Link key={label} href={href} className="block hover:text-white/70">{label}</Link>)}</div></div>; }

function NavLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="rounded-full px-3 py-2 transition hover:bg-[#eef5ff] hover:text-[#111827]">{children}</Link>; }
function MenuLink({ href, title, body }: { href: string; title: string; body: string }) { return <Link href={href} className="block rounded-xl px-3 py-2.5 transition hover:bg-[#eef5ff]"><p className="text-xs font-semibold text-[#111827]">{title}</p><p className="mt-0.5 text-[11px] text-[#94a3b8]">{body}</p></Link>; }
