import type {
  QueryExecutionPlan,
  QueryRouteDecision,
  SourceConfidenceLabel,
  SourceCrossVerification,
  SourceEvidenceRole,
  SourceFreshness,
  SourceVerification,
} from "@/lib/types";

export interface Message {
  id: number;
  serverId?: string;
  role: "user" | "assistant";
  content: string;
  streaming?: boolean;
  feedback?: "up" | "down" | null;
  reported?: boolean;
  emphasis?: "default" | "highlight";
  badge?: string;
  /** Data URL for an image generated by the composer image action. */
  imageUrl?: string;
  imageAttachments?: MessageImageAttachment[];
  artifactAttachment?: MessageArtifactAttachment;
  contextMentions?: MessageContextMention[];
  resources?: MessageResource[];
  /** Answer-grounded suggestions generated after the response completes. */
  followUps?: string[];
  /** User-facing route summary; never contains hidden chain-of-thought. */
  route?: QueryRouteDecision;
  /** Bounded tool/activity steps shown in the Resources drawer. */
  plan?: QueryExecutionPlan;
  /** Keep the public answer-building activity available after streaming completes. */
  showReasoningSummary?: boolean;
  /** End-to-end request duration reported by the query pipeline. */
  durationMs?: number;
  /** Fast research mode used by the composer. */
  fastMode?: boolean;
  replyTo?: MessageReplyReference;
}

export interface MessageImageAttachment {
  artifactId: string;
  filename: string;
  mimeType: string;
}

export interface MessageArtifactAttachment {
  artifactId: string;
  title: string;
  filename: string;
  mimeType: string;
}

export interface MessageContextMention {
  kind:
    | "memory" | "workspace" | "project" | "agent" | "file" | "connector"
    | "web" | "skill" | "mcp_server" | "github_repository" | "document" | "api" | "database"
    | "skills" | "connectors";
  id: string;
  label: string;
}

export type ChatActivityKind =
  | "routing"
  | "memory"
  | "document"
  | "image"
  | "web"
  | "sources"
  | "answer";

export interface ChatActivity {
  kind: ChatActivityKind;
  label: string;
  detail: string;
}

export interface MessageReplyReference {
  messageId: number;
  role: "user" | "assistant";
  content: string;
}

export interface MessageResource {
  title: string;
  url: string;
  domain: string;
  sourceType: string;
  description?: string;
  quote?: string | null;
  imageUrl?: string | null;
  imageLandingUrl?: string | null;
  imageAttribution?: string | null;
  imageLicense?: string | null;
  imageProvider?: string | null;
  citationIndex?: number | null;
  providerLabel?: string;
  canonicalUrl?: string | null;
  faviconUrl?: string | null;
  verification?: SourceVerification;
  trustScore?: number | null;
  trustLabel?: SourceConfidenceLabel | null;
  trustComponents?: Record<string, number>;
  trustExplanation?: string | null;
  confidenceScore?: number | null;
  confidenceLabel?: SourceConfidenceLabel | null;
  confidenceComponents?: Record<string, number>;
  confidenceExplanation?: string | null;
  evidenceRole?: SourceEvidenceRole | null;
  reasonUsed?: string | null;
  influenceScore?: number | null;
  freshness?: SourceFreshness;
  crossVerification?: SourceCrossVerification;
  contentHash?: string | null;
  language?: string | null;
  license?: string | null;
  scoreVersion?: string | null;
}

export interface Model {
  id: string;
  name: string;
  color: string;
  provider: string;
  group?: string;
  caps?: string[];
  disabled?: boolean;
  description?: string;
  dynamic?: boolean;
}

const OPENROUTER_MODELS: Model[] = [
  {
    id: "openrouter-free",
    name: "OpenRouter Auto",
    color: "linear-gradient(135deg,#ff8a3d,#f5c542)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Free", "Auto", "Vision"],
    description: "Free router. Picks an available free OpenRouter model for the request.",
  },
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    color: "linear-gradient(135deg,#ff6b6b,#ffa500)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Free", "OpenRouter"],
    description: "Free OpenRouter model for general chat and coding.",
  },
  {
    id: "kimi-k2.5",
    name: "Kimi K2.5",
    color: "linear-gradient(135deg,#6c63ff,#3ecfcf)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Free", "OpenRouter", "Vision"],
    description: "Free OpenRouter model with vision support.",
  },
  {
    id: "nvidia-nemotron",
    name: "NVIDIA Nemotron",
    color: "linear-gradient(135deg,#76b900,#1a1a1a)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Free", "OpenRouter"],
    description: "Free OpenRouter model optimized for larger-context work.",
  },
  {
    id: "gpt-oss-20b",
    name: "GPT OSS 20B",
    color: "linear-gradient(135deg,#43b89c,#1a6b52)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Open Source", "Free"],
    description: "Free open-source model available through OpenRouter.",
  },
  {
    id: "gpt-oss-120b",
    name: "GPT OSS 120B",
    color: "linear-gradient(135deg,#43b89c,#1a6b52)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Open Source", "Free"],
    description: "Free open-source model available through OpenRouter.",
  },
  {
    id: "grok-4.1-fast",
    name: "Grok 4.1 Fast",
    color: "linear-gradient(135deg,#888,#333)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Free", "OpenRouter"],
  },
  {
    id: "qwen3-14b",
    name: "Qwen3-14B",
    color: "linear-gradient(135deg,#ff9a3c,#e55)",
    provider: "OpenRouter",
    group: "OpenRouter",
    caps: ["Open Source", "Free"],
    description: "Free open-source model available through OpenRouter.",
  },
];

const CONNECTED_PROVIDER_MODELS: Model[] = [
  {
    id: "openai-gpt-5-mini",
    name: "GPT-5 Mini",
    color: "linear-gradient(135deg,#8b5cf6,#3b82f6)",
    provider: "OpenAI",
    group: "OpenAI",
    caps: ["Requires OpenAI", "Paid"],
    disabled: true,
    description: "Enable the OpenAI provider to route chat requests to GPT models.",
  },
  {
    id: "google-gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    color: "linear-gradient(135deg,#22c55e,#06b6d4)",
    provider: "Google",
    group: "Google",
    caps: ["Requires Google AI", "Paid"],
    disabled: true,
    description: "Enable the Google provider to route chat requests to Gemini models.",
  },
  {
    id: "ollama-llama3.1",
    name: "Llama 3.1",
    color: "linear-gradient(135deg,#f97316,#a855f7)",
    provider: "Ollama",
    group: "Ollama",
    caps: ["Local", "Open Source"],
    description: "Run Llama 3.1 through Ollama on this machine.",
  },
  {
    id: "local-qwen2.5",
    name: "Qwen Local",
    color: "linear-gradient(135deg,#14b8a6,#0f766e)",
    provider: "Local",
    group: "Local",
    caps: ["Local", "Open Source"],
    description: "Run the configured Qwen model through Ollama on this machine.",
  },
];

export const MODEL_PROVIDERS = ["OpenRouter", "OpenAI", "Google", "Ollama", "Local"] as const;

export const MODELS: Model[] = [...OPENROUTER_MODELS, ...CONNECTED_PROVIDER_MODELS];

export const OPENROUTER_AUTO_MODEL: Model = MODELS[0];
