import Link from "next/link";
import { ArrowRight, BrainCircuit, Check, ShieldCheck } from "lucide-react";
import { PublicDocsShell } from "@/components/public-docs-shell";

export default function BrainPage() { return <PublicDocsShell><main>
  <section className="border-b border-[#dbe3ee] px-5 py-24 sm:px-8 lg:py-36"><div className="mx-auto grid max-w-[1120px] gap-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#1769e0]">New · TrueMemory Brain</p><h1 className="mt-5 text-5xl font-semibold tracking-[-.065em] sm:text-7xl">A living memory for every agent.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#64748b]">Give your applications a shared, scoped memory that learns from conversations, retrieves the right context, and stays accountable to the workspace it belongs to.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="rounded-md bg-[#1769e0] px-5 py-3 text-sm font-semibold text-white">Build with TrueMemory <ArrowRight className="ml-1 inline size-4" /></Link><Link href="/docs" className="rounded-md border border-[#cbd5e1] px-5 py-3 text-sm font-semibold">Read the docs</Link></div></div><div className="relative overflow-hidden rounded-2xl border border-[#cbd5e1] bg-white p-5 shadow-[0_18px_60px_rgba(15,23,42,.08)]"><div className="flex items-center gap-3 border-b border-[#e2e8f0] pb-4"><span className="grid size-9 place-items-center rounded-full bg-[#e8f0ff] text-[#1769e0]"><BrainCircuit className="size-5" /></span><div><p className="text-sm font-semibold">TrueMemory Brain</p><p className="text-xs text-[#94a3b8]">workspace / product-team</p></div><span className="ml-auto size-2 rounded-full bg-emerald-500" /></div><div className="space-y-3 py-5"><div className="ml-auto max-w-[75%] rounded-xl bg-[#f1f5f9] p-3 text-sm text-[#475569]">What did we decide about the launch?</div><div className="max-w-[84%] rounded-xl border border-[#bfdbfe] bg-[#eff6ff] p-3 text-sm leading-6 text-[#334155]"><span className="font-semibold text-[#1769e0]">Retrieved memory</span><br />The team chose a staged release with workspace-level access and an explicit rollback path.</div><div className="flex flex-wrap gap-2 pt-2 text-[10px] uppercase tracking-[.12em] text-[#64748b]"><span className="rounded-full bg-[#f1f5f9] px-2 py-1">source: meeting</span><span className="rounded-full bg-[#f1f5f9] px-2 py-1">scope: product-team</span><span className="rounded-full bg-[#f1f5f9] px-2 py-1">confidence: tracked</span></div></div></div></div></section>
  <section className="mx-auto max-w-[1120px] px-5 py-24 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#64748b]">How it works</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-[-.05em]">Context that behaves like infrastructure.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-[#dbe3ee] bg-[#dbe3ee] md:grid-cols-3">{[["01","Remember","Write durable context with provenance, confidence, and workspace scope."],["02","Retrieve","Search and retrieve the memories an agent needs for the current task."],["03","Respect boundaries","Authorization, agent bindings, and workspace isolation stay at the API boundary."]].map(([n,t,b]) => <div key={n} className="bg-white p-7"><span className="font-mono text-xs text-[#1769e0]">{n}</span><h3 className="mt-12 text-lg font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[#64748b]">{b}</p></div>)}</div></section>
  <section className="border-y border-[#dbe3ee] bg-white"><div className="mx-auto grid max-w-[1120px] gap-12 px-5 py-24 sm:px-8 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#1769e0]">Built for trust</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Memory with a visible boundary.</h2></div><div className="space-y-5 text-sm leading-7 text-[#64748b]"><p><Check className="mr-2 inline size-4 text-emerald-600" />Scoped tokens and workspace bindings are enforced before memory operations.</p><p><ShieldCheck className="mr-2 inline size-4 text-emerald-600" />The platform exposes REST and MCP interfaces without coupling clients to backend internals.</p><Link href="/docs#isolation" className="inline-flex items-center font-semibold text-[#1769e0]">Read isolation docs <ArrowRight className="ml-1 size-4" /></Link></div></div></section>
</main></PublicDocsShell>; }
