"use client";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { buildAuthHeaders, credentialedFetch } from "@/lib/auth";
export function KeyDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (value: boolean) => void }) {
  const [name, setName] = useState(""); const [days, setDays] = useState("90"); const [token, setToken] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [copied, setCopied] = useState(false);
  async function create(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { const response = await credentialedFetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/auth/api-tokens`, { method: "POST", headers: { ...buildAuthHeaders(), "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim(), scopes: ["memory"], expires_days: Number(days) }) }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.detail === "string" ? data.detail : "Unable to create a key. Check your connection and permissions."); if (!(data.token || data.value)) throw new Error("The server did not return a key."); setToken(data.token || data.value); } catch (err) { setError(err instanceof Error ? err.message : "Could not create key."); } finally { setBusy(false); }
  }
  return <Dialog open={open} onOpenChange={value => { if (!busy) { onOpenChange(value); if (!value) { setToken(""); setError(""); setCopied(false); } } }}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{token ? "Your API key is ready" : "Create API key"}</DialogTitle><DialogDescription>{token ? "Copy this secret now. It will not be shown again after closing." : "Create a real credential with memory access for your application."}</DialogDescription></DialogHeader>{token ? <div className="space-y-4"><code className="block break-all rounded-lg border p-4">{token}</code><button className="rounded-lg border px-4 py-3" onClick={async () => { try { await navigator.clipboard.writeText(token); setCopied(true); } catch { setError("Clipboard unavailable. Select and copy the key above."); } }}>{copied ? "Copied" : "Copy secret key"}</button></div> : <form onSubmit={create} className="space-y-4"><label className="block">Key name<input required maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="production-agent" className="mt-2 block w-full rounded-lg border bg-transparent p-3" /></label><label className="block">Expires<select value={days} onChange={e => setDays(e.target.value)} className="mt-2 block w-full rounded-lg border bg-background p-3"><option value="30">30 days</option><option value="90">90 days</option><option value="365">1 year</option></select></label><div className="rounded-lg border p-3 text-sm">Scope: <strong>memory</strong><p className="mt-1 text-muted-foreground">Uses the memory permission supported by your API.</p></div><button disabled={busy || !name.trim()} className="w-full rounded-lg bg-primary px-4 py-3 text-primary-foreground disabled:opacity-50">{busy ? "Creating…" : "Create key"}</button></form>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</DialogContent></Dialog>;
}
